# Generated by Django 3.2.8 on 2022-04-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220315_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land_details',
            old_name='hash_value',
            new_name='current_owner',
        ),
        migrations.RenameField(
            model_name='land_details',
            old_name='id_unique',
            new_name='land_id',
        ),
        migrations.RenameField(
            model_name='land_details',
            old_name='new_buyer',
            new_name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='land_details',
            name='previous_buyer',
        ),
    ]
